content:
  - name: ggPosts
    label: Coffee Posts
    path: src/posts
    filename: '{fields.title}.md'
    type: collection
    view:
      fields: [coffeeImage, title, date]
    fields:
      - name: tags
        label: Tags
        type: string
        
      - name: roaster
        label: Roaster
        type: string

      - name: title
        label: Title
        type: string

      - name: date
        label: Publication Date
        type: date
        options:
          format: yyyy-MM-dd

      - name: coffeeImage
        label: Coffee Image
        type: image

      - name: origin
        label: Origin
        type: string

      - name: varietal
        label: Varietal
        type: string

      - name: process
        label: Process
        type: string

      - name: elevation
        label: Elevation
        type: string

      - name: notes
        label: Notes
        type: string

      - name: aromaGeneral
        label: Aroma General
        type: string

      - name: aromaSpecific
        label: Aroma Specific
        type: string

      - name: acidityGeneral
        label: Acidity General
        type: string

      - name: aciditySpecific
        label: Acidity Specific
        type: string

      - name: mouthfeelGeneral
        label: Mouthfeel General
        type: string

      - name: mouthfeelSpecific
        label: Mouthfeel Specific
        type: string

      - name: flavorGeneral
        label: Flavor General
        type: string

      - name: flavorSpecific
        label: Flavor Specific
        type: string

      - name: finishGeneral
        label: Finish General
        type: string

      - name: finishSpecific
        label: Finish Specific
        type: string

      - name: overallGeneral
        label: Overall General
        type: string

      - name: overallSpecific
        label: Overall Specific
        type: string

  - name: glossaryEntries
    label: Glossary Entries
    path: src/_data/glossaryentries.json
    type: file
    format: json
    list: true
    fields:
    - name: term
      label: Term
      type: string

    - name: definition
      label: Definition
      type: string

  - name: roasters
    label: Roasters
    path: src/_data/roasters.json
    type: file
    format: json
    list: true
    fields:
    - name: name
      label: Name
      type: string

    - name: website
      label: Website
      type: string
      pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$

    - name: logo
      label: Logo
      type: image
      description: maintain naming convention starting with 'roaster-logo_'

    - name: city
      label: City
      type: string

    - name: state
      label: State
      type: string

    - name: description
      label: Description
      type: string

    - name: extraInfo
      label: Extra Info
      type: object
      fields:
      - name: est
        label: Established year
        type: string

      - name: awards
        label: Awards
        type: boolean

      - name: notable
        label: Notables
        type: string
        list: true

      - name: ownership
        label: Ownership
        type: string

      - name: memberships
        label: Memberships
        type: string
        list: true

    - name: johnsSeal
      label: Johns seal
      type: boolean
      
media:
  input: src/img
  output: /img